Lab1
puzzzik/IU5-iOS-2022 pull request #1
Opened 2022-02-22 09:11 UTC by puzzzik

## Товарищ, твой PR - твоя гордость!

- [ ] Убедись, что все тесты прошли успешно.
- [ ] Проверь, что Pull Request таргетоирован в ТВОЙ ФОРКНУТЫЙ main
- [ ] Заполни отчет по лабораторной работе в Google форме
- [ ] Улыбнись, ведь ты приобрел новые навыки)

## Важно!

После того, как ты заполнишь отчет по лабе, я или Юра поревьюим его, и напишем комментарии к коду, если будут вопросы.

Когда ты увидишь коментарий "Все ОК, мержи", можешь смержить PR.

- [ ] Ты увидел "Все ОК, мержи"?

2022-02-25 17:35 UTC, YuryBogdanov requested changes
Красавчик, но нужно чуть-чуть поправить) сделаешь и максимальный балл у тебя в кармане ;)

2022-02-25 17:35 UTC, YuryBogdanov commented on LABS/LAB_1/ArrayToString.swift
> +        guard array.count != 1 else {
Тут лучше `> 1`, т.к. иначе под это условие подходят и 0, и -1, и -2, и 5 и тд

2022-02-25 17:35 UTC, YuryBogdanov commented on LABS/LAB_1/ArrayToString.swift
> +        var tempString: String = ""
в этих строках можно опустить `: String` и `: Int`, компилятор сам додумается до этих типов через Type Inference

2022-02-25 17:35 UTC, YuryBogdanov commented on LABS/LAB_1/ArrayToString.swift
> +        while i < array.count - 1 {
тут лучше подойдет 
```
for i in 0..<array.count { }
```
плюс, тут -1 лишняя, т.к. у тебя строгое равенство. То есть с -1 ты просто последний элемент не обработаешь.

2022-02-25 17:35 UTC, YuryBogdanov commented on LABS/LAB_1/ArrayToString.swift
> +            while i < array.count - 1, array[i] + 1 == array[i + 1] {
а вот это вообще лишнее) задачу можно решить через один цикл

2022-02-25 17:35 UTC, YuryBogdanov commented on LABS/LAB_1/NumberToArray.swift
> +        var myNumber = abs(number)
можно было этого не делать и не использовать метод `signum()` на 36-й строке. Знак у тебя остался бы от исходного числа

2022-02-25 17:35 UTC, YuryBogdanov commented on LABS/LAB_1/SquareSum.swift
> +        guard arrayOfNumber.count > 0 else {
isEmpty

2022-02-25 17:35 UTC, YuryBogdanov commented on LABS/LAB_1/SquareSum.swift
> +        arrayOfNumber.forEach { number in
Это можно решить через метод reduce
Посмотри в документации как он работает, и сделай красиво :)

2022-02-27 08:05 UTC, puzzzik commented on LABS/LAB_1/ArrayToString.swift
> +        var tempString: String = ""
А на лекции просто сказали же, что компилятор работает быстрее, если указывать типы вручную

2022-02-27 08:06 UTC, puzzzik commented on LABS/LAB_1/ArrayToString.swift
> +        while i < array.count - 1 {
А тут -1 я сделал, потому что в цикле я обращаюсь к array[i+1]

2022-02-27 08:38 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +        var tempString: String = ""
Все так, в подобных случаях это must have

let int = 42
let double = 42 as Double
let float: Float = 42
let cgFloat = CGFloat(42)

2022-02-27 08:38 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +        var tempString: String = ""
а тут можно опустить
P.S. респект за внимательность

2022-02-27 19:09 UTC, YuryBogdanov commented on LABS/LAB_1/SquareSum.swift
> +        let totalSquareSum = arrayOfNumber.reduce(0, {x, y in
да, молодец
можно чуть красивее сделать:
```
let totalSquareSum = arrayOfNumber.reduce(0) { $0 + $1 * $1 }
```
Это называется trailing closure (когда в списке параметров функции есть замыкание, и оно в конце - можно писать его за скобками функции)

2022-02-27 20:35 UTC, puzzzik commented
Могу мержить?

2022-02-28 06:44 UTC, merged