Lab6
puzzzik/IU5-iOS-2022 pull request #7
Opened 2022-04-03 17:45 UTC by puzzzik

## Товарищ, твой PR - твоя гордость!

- [ ] Убедись, что все тесты прошли успешно.
- [ ] Проверь, что Pull Request таргетоирован в ТВОЙ ФОРКНУТЫЙ main
- [ ] Заполни отчет по лабораторной работе в Google форме
- [ ] Улыбнись, ведь ты приобрел новые навыки)

## Важно!

После того, как ты заполнишь отчет по лабе, я или Юра поревьюим его, и напишем комментарии к коду, если будут вопросы.

Когда ты увидишь коментарий "Все ОК, мержи", можешь смержить PR.

- [ ] Ты увидел "Все ОК, мержи"?

2022-04-04 19:28 UTC, YuryBogdanov requested changes
В целом очень даже неплохо.
Нужно:
1. Убрать NotificationCenter, на лекции разобрали как
2. Исправить все отступы (попробуй выделить весь текст в файле и хоткей Ctrl+I)
3. Настройку данных через DisplayData
4. Плюс все остальное :)

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +	var cityName: String = ""
уровень доступа (private)  
let vs var
force unwrap

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +		NotificationCenter.default.addObserver(self,
Несмотря на то, что в некоторых моментах использовать отправку нотификаций в iOS можно (даже Apple так делает), их использование очень ограничвается, ибо дебажить их сложно (ты не знаешь кто тебе отправил нотификацию, дебажить такой код можно долго). 
Поэтому убираем и делаем иначе :)

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +		                                       name: NSNotification.Name("userDidTypedCityName"),
didType, если уж на то пошло)

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +	weak var output: WeatherInteractorOutput!
отступы по всему проекту исправить надо

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +					print("Error: \(error)")
тут ассерт тоже

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Services/NetworkSerivce.swift
> +					completion(.success(data))
надо обернуть в 
```
DispatchQueue.main.async {
    completion(.success(data))
}
```

так как URLSession возвращает свой комплишн на бэкграунд очереди

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Services/NetworkSerivce.swift
> +		DispatchQueue.global(qos: .userInitiated).async { [weak self] in
не надо, под капотом URLSession оборачивает в свою очередь

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +class WeatherTableViewCell: UITableViewCell {
final

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +		enum propertyResult {
названия enum-ов с больших букв

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +		propertyResultLabel.frame = CGRect(x: propertyNameLabel.frame.maxX + FrameSizes.propertyResult.x,
Вообще вёрстка на фреймах обычно должна быть чем-то оправдана. Например, ячейки в таблице/коллекции слишком сложные. Тут у нас довольно простое все, поэтому давай все на констрейнты переделаем, тут довольно просто будет.

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +		propertyResultLabel.numberOfLines = 2
в константы

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +	func configure(propertyName: String, propertyResult: String?) {
оба параметра в DisplayData и настраивать через неё

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +		guard propertyResult != nil else {
свойство `text` у лейбла принимает опциональный текст, эта проверка излишняя

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +		enum textField {
у тебя константы только про текст филд, можно эту вложенность не делать) а если и делать, то с большой буквы enum обзывать

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +		super.prepareForReuse()
если не добавляешь никаких действий в метод, то нет смысла его переопределять)
удалить

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +		textField.frame = CGRect(x: Constants.textField.x,
переделать на констрейнты

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +		NotificationCenter.default.post(name: NSNotification.Name("textFieldDidEditingEnd"),
вот тут надо либо делегата позвать, как на лекции обсуждали, либо через action

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherViewController.swift
> +			static let topAnchor: CGFloat = 40
это не anchor, это offset (следующая константа тоже)

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherViewController.swift
> +			                                  constant: Constants.tableConstraints.bottomAnchor),
а зачем тут и в top применять константу? у тебя ведь safeArea и так как надо расположит таблицу

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherViewController.swift
> +		guard let header = tableView.dequeueReusableHeaderFooterView(
у тебя эта view будет показываться для каждой секции, если вдруг у тебя их будет больше одной, а это некорректно будет
нужно либо проверять индекс, и показывать только для нулевой секции, либо (предпочтительнее) посмотреть tableHeaderView (глобальный хедер всей таблицы)

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherViewController.swift
> +		DispatchQueue.main.async { [weak self] in
не, оборачивай вызов мейн еще в интеракторе/презентере, тут все уже на мейне должно быть

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Presenter/WeatherPresenter.swift
> +	]
давай на enum переделаем

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Presenter/WeatherPresenter.swift
> +		NotificationCenter.default.addObserver(self, selector: #selector(getCityName), name: NSNotification.Name("textFieldDidEditingEnd"), object: nil)
убираем)

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Presenter/WeatherPresenter.swift
> +		1
в константы

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Presenter/WeatherPresenter.swift
> +	func cellForRow(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
сущности UIKit (UITableView, UITableViewCell) не должны вылезать за пределы ViewController-а. Например, завтра будем писать вью на AppKit для macOS, можно будет переиспользовать презентер. А если в нем будет UIKit, то не переиспользовать не получится.

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Presenter/WeatherPresenter.swift
> +		propertyResults[9] = forecast.system.country
прихранивать данные для показа - ок
делать это в словаре - не ок, давай сделаем фабрику и будем подготавливать displayData для ячеек

2022-04-04 19:28 UTC, YuryBogdanov commented on LABS/LAB_6/Services/NetworkRequestFactory.swift
> +			URLQueryItem(name: "appid", value: Constants.apiKey)
молодец, что поразбирался с апишкой :)

2022-04-05 14:32 UTC, puzzzik commented on LABS/LAB_6/View/WeatherViewController.swift
> +			                                  constant: Constants.tableConstraints.bottomAnchor),
Мне хотелось таблицу опустить пониже
Мне кажется, так выглядит лучше
Но можно и через UIEdgeInset() сделать, если в якорях не стоит

2022-04-05 16:25 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherViewController.swift
> +			                                  constant: Constants.tableConstraints.bottomAnchor),
"Пониже" - это чтобы контент скроллится до нижнего края экрана, а не обрезался над home indicator-ом (чёрная полоска внизу экрана)?

2022-04-05 18:45 UTC, puzzzik commented on LABS/LAB_6/View/WeatherViewController.swift
> +			                                  constant: Constants.tableConstraints.bottomAnchor),
Нет, просто опустить таблицу, чтобы она начиналась не с самого верха экрана (допустимого), а чуть-чуть пониже

Просто лично мне всегда нравилось больше, когда контент находится посередине экрана, чтобы палец не тянуть наверх

2022-04-05 20:31 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherViewController.swift
> +			                                  constant: Constants.tableConstraints.bottomAnchor),
Так устройства разные бывают) если у тебя лопата вроде 12 pro max, то это желание понятно, но если у тебя 12 mini, то ты отжираешь место для контента, у многих владельцев маленьких телефонов от этого очень сильно горит)
А чтобы палец не тянуть есть такая фишка как Reachability. На айфонах с кнопкой - два раза тапнуть по кнопке "Домой", на десятке и новее - провести вниз по индикатору "домой".

2022-04-07 16:49 UTC, puzzzik commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +	var cityName: String = ""
Done

2022-04-07 16:49 UTC, puzzzik commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +		NotificationCenter.default.addObserver(self,
Done

2022-04-07 16:49 UTC, puzzzik commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +		                                       name: NSNotification.Name("userDidTypedCityName"),
Done

2022-04-07 16:49 UTC, puzzzik commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +	weak var output: WeatherInteractorOutput!
Done

2022-04-07 16:49 UTC, puzzzik commented on LABS/LAB_6/Services/NetworkSerivce.swift
> +					completion(.success(data))
Done

2022-04-07 16:49 UTC, puzzzik commented on LABS/LAB_6/Services/NetworkSerivce.swift
> +		DispatchQueue.global(qos: .userInitiated).async { [weak self] in
Done

2022-04-07 16:50 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +class WeatherTableViewCell: UITableViewCell {
Done

2022-04-07 16:50 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +		enum propertyResult {
Done

2022-04-07 16:50 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +		propertyResultLabel.frame = CGRect(x: propertyNameLabel.frame.maxX + FrameSizes.propertyResult.x,
Done

2022-04-08 06:05 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +		propertyResultLabel.numberOfLines = 2
Done

2022-04-08 06:05 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +	func configure(propertyName: String, propertyResult: String?) {
Done

2022-04-08 06:06 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewCell.swift
> +		guard propertyResult != nil else {
Done

2022-04-08 06:06 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +		enum textField {
Done

2022-04-08 06:06 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +		super.prepareForReuse()
Done

2022-04-08 06:06 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +		textField.frame = CGRect(x: Constants.textField.x,
Done

2022-04-08 06:06 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +		NotificationCenter.default.post(name: NSNotification.Name("textFieldDidEditingEnd"),
Done

2022-04-08 06:07 UTC, puzzzik commented on LABS/LAB_6/View/WeatherViewController.swift
> +			static let topAnchor: CGFloat = 40
Done

2022-04-08 06:07 UTC, puzzzik commented on LABS/LAB_6/View/WeatherViewController.swift
> +			                                  constant: Constants.tableConstraints.bottomAnchor),
Done

2022-04-08 06:07 UTC, puzzzik commented on LABS/LAB_6/View/WeatherViewController.swift
> +		guard let header = tableView.dequeueReusableHeaderFooterView(
Done

2022-04-08 06:07 UTC, puzzzik commented on LABS/LAB_6/View/WeatherViewController.swift
> +		DispatchQueue.main.async { [weak self] in
Done

2022-04-08 06:07 UTC, puzzzik commented on LABS/LAB_6/Presenter/WeatherPresenter.swift
> +	]
Done

2022-04-08 06:07 UTC, puzzzik commented on LABS/LAB_6/Presenter/WeatherPresenter.swift
> +		NotificationCenter.default.addObserver(self, selector: #selector(getCityName), name: NSNotification.Name("textFieldDidEditingEnd"), object: nil)
Done

2022-04-08 06:07 UTC, puzzzik commented on LABS/LAB_6/Presenter/WeatherPresenter.swift
> +		1
Done

2022-04-08 06:08 UTC, puzzzik commented on LABS/LAB_6/Presenter/WeatherPresenter.swift
> +	func cellForRow(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
Done

2022-04-08 06:08 UTC, puzzzik commented on LABS/LAB_6/Presenter/WeatherPresenter.swift
> +		propertyResults[9] = forecast.system.country
Done

2022-04-10 19:45 UTC, YuryBogdanov requested changes
Уже сильно лучше
Немного похулиганил с расстановкой свойств и методов - надо поправить (и привыкать к правильной расстановке)

2022-04-10 19:45 UTC, YuryBogdanov commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +    private let networkService: NetworkServiceProtocol!
Свойства **всегда** **перед** конструктором (после конструктора - только методы, там никогда не должно быть свойств, даже computed), посмотри как я это делал в классах Weather модуля

2022-04-10 19:45 UTC, YuryBogdanov commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +                assertionFailure("Error: \(error)")
В учебном проекте это ок, но в пет-проектах и, тем более, в продакшене, тут надо было бы сообщить презентеру о том, что получили ошибку и показать пользователю ошибку любым способом (алерт или заглушка вместо таблицы). Тоже самое касается 69-й строки.

Править не нужно.

2022-04-10 19:45 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +//
Закомментированного кода быть не должно

2022-04-10 19:45 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +        let action: ((String?) -> Void)?
опциональность тут в обоих случаях оправдана?

2022-04-10 19:45 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +    func configure(displayData: DisplayData) {
В правильное место нужно этот метод поставить

2022-04-10 19:45 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +//            textField.widthAnchor.constraint(equalTo: widthAnchor, constant: -Constants.leadingOffset*2)
Закомментированного кода быть не должно

2022-04-10 19:45 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherViewController.swift
> +    override func viewDidLoad() {
в правильное место этот метод надо поместить

2022-04-10 19:45 UTC, YuryBogdanov commented on LABS/LAB_6/View/WeatherViewController.swift
> +
лишняя пустая строка

2022-04-10 19:45 UTC, YuryBogdanov commented on LABS/LAB_6/WeatherBuilder.swift
> +        let locationManager = LocationManager()
отступы снова

2022-04-14 17:33 UTC, puzzzik commented on LABS/LAB_6/WeatherBuilder.swift
> +        let locationManager = LocationManager()
done

2022-04-14 17:33 UTC, puzzzik commented on LABS/LAB_6/View/WeatherViewController.swift
> +
done

2022-04-14 17:34 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +//            textField.widthAnchor.constraint(equalTo: widthAnchor, constant: -Constants.leadingOffset*2)
done

2022-04-14 17:34 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +//
done

2022-04-14 17:34 UTC, puzzzik commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +                assertionFailure("Error: \(error)")
В 8 лабе будет!

2022-04-14 17:34 UTC, puzzzik commented on LABS/LAB_6/Interactor/WeatherInteractor.swift
> +    private let networkService: NetworkServiceProtocol!
done

2022-04-14 17:47 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +    func configure(displayData: DisplayData) {
done

2022-04-14 17:48 UTC, puzzzik commented on LABS/LAB_6/View/WeatherTableViewHeader.swift
> +        let action: ((String?) -> Void)?
done

2022-04-14 17:48 UTC, puzzzik commented on LABS/LAB_6/View/WeatherViewController.swift
> +    override func viewDidLoad() {
done

2022-05-17 17:18 UTC, merged